---
ID: "cbf667b5-cd79-4e66-b28a-fc0f1002e73c"
Parent: "86ba13fc-49fe-43dd-916a-431937878eb7"
Template: "86ba13fc-49fe-43dd-916a-431937878eb7"
Path: /sitecore/templates/HMPPS/Pages/Homepage/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {02E48DB2-8E6E-4141-B759-D508212202B7}
    {74E2B01C-18F1-4FE5-A9BE-3D6B5AFB2FAA}
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{DE7856F7-B9AC-4A84-B01E-BF66F978BBC6}">
        <p
          uid="{5D1DCDF7-9DCA-4937-AFDC-6D60088209B9}"
          key="feature-blocks-row-1"
          md="/sitecore/layout/Placeholder Settings/HMPPS/feature-blocks" />
        <p
          uid="{DFDA4C4A-415A-4583-AA0D-42D74B9A209F}"
          key="feature-blocks-row-2"
          md="/sitecore/layout/Placeholder Settings/HMPPS/feature-blocks" />
        <p
          uid="{A02D9D0C-4137-4FE9-9675-62E1AEAA2962}"
          key="feature-blocks-row-3"
          md="/sitecore/layout/Placeholder Settings/HMPPS/feature-blocks" />
        <r
          id="{8B907AEE-8268-4CED-9162-F776C76B6239}"
          ph="content"
          uid="{6C91C252-A142-40AB-B378-D23958697170}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170901T152749Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\e3_MihaelaR
